import { db } from './drizzle';
import { events, members } from './schema';
import { eq, and } from 'drizzle-orm';

// Seed 2026 events for CUPE Local 100 (union id: 26)
async function seedCUPE100Events() {
  const unionId = 26;

  // Get the first owner member to use as createdBy
  const [adminMember] = await db
    .select()
    .from(members)
    .where(
      and(
        eq(members.unionId, unionId),
        eq(members.role, 'owner')
      )
    )
    .limit(1);

  if (!adminMember) {
    console.error('No owner found for union id 26. Please run the CUPE 100 demo seed first.');
    process.exit(1);
  }

  const createdBy = adminMember.userId;
  console.log(`Creating 2026 events for CUPE Local 100 (union id: ${unionId}) with createdBy: ${createdBy}`);

  const eventsData = [
    // ── JANUARY ──
    {
      unionId,
      title: 'January General Membership Meeting',
      description: 'Monthly general membership meeting to kick off the new year. Hear reports from the executive, review the year\'s agenda, and discuss member priorities for 2026.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-01-08T00:00:00'),
      endDate: new Date('2026-01-08T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'New Year Executive Board Meeting',
      description: 'Executive board meeting to finalize 2026 priorities, budget review, and assign committee responsibilities for the year.',
      location: 'Union Hall — Conference Room A',
      startDate: new Date('2026-01-06T00:00:00'),
      endDate: new Date('2026-01-06T00:00:00'),
      startTime: '17:00',
      endTime: '19:00',
      isAllDay: false,
      isPrivate: true,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Steward Training — Grievance Handling 101',
      description: 'An introduction to grievance handling for new stewards. Topics include recognizing grievable situations, drafting grievances, timelines, and member representation best practices. Lunch provided.',
      location: 'Union Hall — Training Room',
      startDate: new Date('2026-01-17T00:00:00'),
      endDate: new Date('2026-01-17T00:00:00'),
      startTime: '09:00',
      endTime: '16:00',
      isAllDay: false,
      isPrivate: true,
      category: 'training',
      createdBy,
    },
    {
      unionId,
      title: 'Safety Committee Meeting — January',
      description: 'Monthly safety committee meeting. Review winter workplace incident reports, discuss cold-weather PPE compliance, and plan upcoming safety inspections.',
      location: 'Union Hall — Conference Room B',
      startDate: new Date('2026-01-13T00:00:00'),
      endDate: new Date('2026-01-13T00:00:00'),
      startTime: '14:00',
      endTime: '15:30',
      isAllDay: false,
      isPrivate: true,
      category: 'meeting',
      createdBy,
    },

    // ── FEBRUARY ──
    {
      unionId,
      title: 'February General Membership Meeting',
      description: 'Monthly general membership meeting. Updates on contract enforcement, bargaining unit updates, and Q&A with the executive.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-02-05T00:00:00'),
      endDate: new Date('2026-02-05T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Black History Month Celebration',
      description: 'Join CUPE Local 100 in celebrating Black History Month. Special program featuring guest speakers, a photo exhibition, and a community potluck. All members and their families are welcome.',
      location: 'Community Centre — 456 Unity Street',
      startDate: new Date('2026-02-21T00:00:00'),
      endDate: new Date('2026-02-21T00:00:00'),
      startTime: '12:00',
      endTime: '16:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Financial Literacy Workshop',
      description: 'Free workshop for members on retirement planning, understanding your pension, budgeting tips, and debt management. Open to members and their spouses or partners.',
      location: 'Ottawa Public Library — Meeting Room 3',
      startDate: new Date('2026-02-14T00:00:00'),
      endDate: new Date('2026-02-14T00:00:00'),
      startTime: '10:00',
      endTime: '12:00',
      isAllDay: false,
      isPrivate: false,
      category: 'training',
      createdBy,
    },

    // ── MARCH ──
    {
      unionId,
      title: 'March General Membership Meeting',
      description: 'Monthly general membership meeting. Executive reports, election committee update, and ratification discussion.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-03-05T00:00:00'),
      endDate: new Date('2026-03-05T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: "International Women's Day Rally",
      description: 'Join CUPE Local 100 in marching for gender equity, equal pay, and safer workplaces. Meet at the union hall before the rally. Signs and banners will be provided.',
      location: 'Starting at Union Hall — proceeding to City Hall Plaza',
      startDate: new Date('2026-03-08T00:00:00'),
      endDate: new Date('2026-03-08T00:00:00'),
      startTime: '11:00',
      endTime: '14:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Steward Advanced Training — Contract Interpretation',
      description: 'Two-day advanced training for experienced stewards. Deep dive into contract language, discipline and discharge procedures, and arbitration preparation. Lunch provided both days.',
      location: 'Union Hall — Training Room',
      startDate: new Date('2026-03-14T00:00:00'),
      endDate: new Date('2026-03-15T00:00:00'),
      startTime: '09:00',
      endTime: '16:00',
      isAllDay: false,
      isPrivate: true,
      category: 'training',
      createdBy,
    },
    {
      unionId,
      title: 'Community Food Drive — Spring Edition',
      description: 'Help us fight food insecurity in our community. Volunteers needed to sort and pack donations at the Ottawa Food Bank. T-shirts and gloves provided.',
      location: 'Ottawa Food Bank — 1317 Coldrey Ave',
      startDate: new Date('2026-03-28T00:00:00'),
      endDate: new Date('2026-03-28T00:00:00'),
      startTime: '08:00',
      endTime: '12:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },

    // ── APRIL ──
    {
      unionId,
      title: 'Annual General Meeting (AGM)',
      description: 'Annual General Meeting of CUPE Local 100. Agenda includes financial reports, executive committee reports, resolutions and by-law amendments, and elections for vacant executive positions. Lunch will be provided. All members in good standing are encouraged to attend.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-04-11T00:00:00'),
      endDate: new Date('2026-04-11T00:00:00'),
      startTime: '10:00',
      endTime: '14:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Day of Mourning — Workers Memorial Day',
      description: 'CUPE Local 100 commemorates workers killed or injured on the job. A moment of silence will be held at 11 AM. Members are encouraged to wear black armbands during their shift.',
      location: 'Union Hall — Front Steps',
      startDate: new Date('2026-04-28T00:00:00'),
      endDate: new Date('2026-04-28T00:00:00'),
      startTime: '10:45',
      endTime: '11:15',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'April General Membership Meeting',
      description: 'Monthly general membership meeting. Post-AGM follow-up, newly elected executive introductions, and member Q&A.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-04-02T00:00:00'),
      endDate: new Date('2026-04-02T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },

    // ── MAY ──
    {
      unionId,
      title: 'May Day Rally — International Workers Day',
      description: 'March with CUPE Local 100 on May Day in solidarity with workers across Canada and the world. Banners, music, and speakers. Meet at Confederation Park.',
      location: 'Confederation Park — 1 Elgin St',
      startDate: new Date('2026-05-01T00:00:00'),
      endDate: new Date('2026-05-01T00:00:00'),
      startTime: '11:00',
      endTime: '14:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'May General Membership Meeting',
      description: 'Monthly general membership meeting. Summer scheduling, dues update, and upcoming events overview.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-05-07T00:00:00'),
      endDate: new Date('2026-05-07T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Health & Safety Week — Information Sessions',
      description: 'Week-long awareness campaign with daily lunch-and-learn sessions on workplace hazards, mental health, ergonomics, and your rights under the OHSA. Free to all members.',
      location: 'Union Hall — Lunchroom',
      startDate: new Date('2026-05-04T00:00:00'),
      endDate: new Date('2026-05-08T00:00:00'),
      startTime: '12:00',
      endTime: '13:00',
      isAllDay: false,
      isPrivate: false,
      category: 'training',
      createdBy,
    },

    // ── JUNE ──
    {
      unionId,
      title: 'June General Membership Meeting',
      description: 'Monthly general membership meeting. Summer work schedule updates, heat-stress policy review, and member concerns.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-06-04T00:00:00'),
      endDate: new Date('2026-06-04T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Annual Summer Picnic',
      description: 'The CUPE Local 100 Annual Summer Picnic! Food, games, music, and prizes for the whole family. Kids activities, barbecue, and a bouncy castle. Free for all members and their families.',
      location: 'Vincent Massey Park — Pavilion 2',
      startDate: new Date('2026-06-20T00:00:00'),
      endDate: new Date('2026-06-20T00:00:00'),
      startTime: '11:00',
      endTime: '16:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Pride at Work Celebration',
      description: 'CUPE Local 100 celebrates Pride Month with a lunch gathering for members, allies, and families. Rainbow flags, solidarity pins, and a short ceremony recognizing 2SLGBTQ+ member contributions.',
      location: 'Union Hall — Main Hall',
      startDate: new Date('2026-06-19T00:00:00'),
      endDate: new Date('2026-06-19T00:00:00'),
      startTime: '12:00',
      endTime: '13:30',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },

    // ── JULY ──
    {
      unionId,
      title: 'Canada Day — Union Hall Closed',
      description: 'The Union Hall offices will be closed on Canada Day. Regular operations resume July 2nd.',
      location: 'Union Hall',
      startDate: new Date('2026-07-01T00:00:00'),
      endDate: new Date('2026-07-01T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'July Executive Board Meeting',
      description: 'Monthly executive board meeting. Mid-year financial review, collective agreement administration updates, and fall planning.',
      location: 'Union Hall — Conference Room A',
      startDate: new Date('2026-07-07T00:00:00'),
      endDate: new Date('2026-07-07T00:00:00'),
      startTime: '17:00',
      endTime: '19:00',
      isAllDay: false,
      isPrivate: true,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Member Bowling Night',
      description: 'A fun casual bowling night for members and their families. Lanes are booked from 7–10 PM. Shoe rentals included. Snacks and non-alcoholic beverages provided.',
      location: 'Capital Bowling Lanes — 1980 Bank St',
      startDate: new Date('2026-07-17T00:00:00'),
      endDate: new Date('2026-07-17T00:00:00'),
      startTime: '19:00',
      endTime: '22:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },

    // ── AUGUST ──
    {
      unionId,
      title: 'Civic Holiday — Union Hall Closed',
      description: 'The Union Hall offices will be closed for the Civic Holiday. Regular operations resume August 4th.',
      location: 'Union Hall',
      startDate: new Date('2026-08-03T00:00:00'),
      endDate: new Date('2026-08-03T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'August General Membership Meeting',
      description: 'Monthly general membership meeting. Back-to-school scheduling update, fall events preview, and any member business.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-08-06T00:00:00'),
      endDate: new Date('2026-08-06T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'New Member Orientation',
      description: 'Welcome orientation for members who joined in the last six months. Learn about your collective agreement, union benefits, how to contact your steward, and how to get involved.',
      location: 'Union Hall — Room 101',
      startDate: new Date('2026-08-20T00:00:00'),
      endDate: new Date('2026-08-20T00:00:00'),
      startTime: '17:30',
      endTime: '19:00',
      isAllDay: false,
      isPrivate: false,
      category: 'training',
      createdBy,
    },

    // ── SEPTEMBER ──
    {
      unionId,
      title: 'Labour Day March & Rally',
      description: 'Celebrate Labour Day with your union! CUPE Local 100 marches with the Ottawa & District Labour Council. Assemble at Lansdowne Park and march to City Hall for the rally and live music.',
      location: 'Lansdowne Park — Aberdeen Pavilion',
      startDate: new Date('2026-09-07T00:00:00'),
      endDate: new Date('2026-09-07T00:00:00'),
      startTime: '10:00',
      endTime: '14:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Labour Day — Union Hall Closed',
      description: 'The Union Hall offices will be closed on Labour Day. Regular operations resume September 8th.',
      location: 'Union Hall',
      startDate: new Date('2026-09-07T00:00:00'),
      endDate: new Date('2026-09-07T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'September General Membership Meeting',
      description: 'Monthly general membership meeting. Fall term kickoff — reviewing priorities, contract enforcement updates, and committee elections.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-09-10T00:00:00'),
      endDate: new Date('2026-09-10T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Collective Bargaining Town Hall',
      description: 'Important town hall to discuss our collective agreement renewal. The bargaining committee will present their strategy and gather member priorities. All approved members are strongly encouraged to attend.',
      location: 'Ottawa Convention Centre — Hall B',
      startDate: new Date('2026-09-24T00:00:00'),
      endDate: new Date('2026-09-24T00:00:00'),
      startTime: '18:00',
      endTime: '20:30',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },

    // ── OCTOBER ──
    {
      unionId,
      title: 'Thanksgiving — Union Hall Closed',
      description: 'The Union Hall offices will be closed for Thanksgiving. Regular operations resume October 13th.',
      location: 'Union Hall',
      startDate: new Date('2026-10-12T00:00:00'),
      endDate: new Date('2026-10-12T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'October General Membership Meeting',
      description: 'Monthly general membership meeting. Bargaining update, ratification vote preparation, and member Q&A.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-10-01T00:00:00'),
      endDate: new Date('2026-10-01T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Halloween Member Social',
      description: 'Costumes welcome! Annual Halloween social for members and families. Candy for the kids, prizes for best costumes, pumpkin carving contest, and haunted tours of the union hall (sort of).',
      location: 'Union Hall — Main Hall',
      startDate: new Date('2026-10-30T00:00:00'),
      endDate: new Date('2026-10-30T00:00:00'),
      startTime: '18:00',
      endTime: '21:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Mental Health First Aid Training',
      description: 'Two-day Mental Health First Aid certification course, accredited through the Mental Health Commission of Canada. Learn to recognize and respond to mental health crises in the workplace. Limited to 20 participants. Lunch provided.',
      location: 'Union Hall — Training Room',
      startDate: new Date('2026-10-17T00:00:00'),
      endDate: new Date('2026-10-18T00:00:00'),
      startTime: '09:00',
      endTime: '16:30',
      isAllDay: false,
      isPrivate: true,
      category: 'training',
      createdBy,
    },

    // ── NOVEMBER ──
    {
      unionId,
      title: 'Remembrance Day — Union Hall Closed',
      description: 'The Union Hall offices will be closed in observance of Remembrance Day. Regular operations resume November 12th.',
      location: 'Union Hall',
      startDate: new Date('2026-11-11T00:00:00'),
      endDate: new Date('2026-11-11T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'November General Membership Meeting',
      description: 'Monthly general membership meeting. Holiday season events planning, year-end financial preview, and committee reports.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-11-05T00:00:00'),
      endDate: new Date('2026-11-05T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Grievance Committee Year-End Review',
      description: 'Annual grievance committee review of all active and closed files. Strategic planning for the new year and outstanding arbitrations.',
      location: 'Union Hall — Conference Room B',
      startDate: new Date('2026-11-19T00:00:00'),
      endDate: new Date('2026-11-19T00:00:00'),
      startTime: '15:00',
      endTime: '18:00',
      isAllDay: false,
      isPrivate: true,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Toy Drive & Community Wrap Party',
      description: 'Help us wrap donated toys for families in need this holiday season. Wrapping paper and supplies provided. Coffee, hot chocolate, and snacks on us.',
      location: 'Union Hall — Main Hall',
      startDate: new Date('2026-11-28T00:00:00'),
      endDate: new Date('2026-11-28T00:00:00'),
      startTime: '10:00',
      endTime: '14:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },

    // ── DECEMBER ──
    {
      unionId,
      title: 'December General Membership Meeting',
      description: 'Year-end general membership meeting. Annual report, financial overview, and planning for the 2027 agenda.',
      location: 'City Hall — Council Chambers, 110 Laurier Ave',
      startDate: new Date('2026-12-03T00:00:00'),
      endDate: new Date('2026-12-03T00:00:00'),
      startTime: '18:00',
      endTime: '20:00',
      isAllDay: false,
      isPrivate: false,
      category: 'meeting',
      createdBy,
    },
    {
      unionId,
      title: 'Annual Holiday Party',
      description: 'Our biggest social event of the year! Dinner, dancing, live music, raffle prizes, and recognition of retiring members. Formal attire encouraged. Tickets available through the union office — members get one free ticket; guests welcome at a nominal cost.',
      location: 'Westin Ottawa — Grand Ballroom, 11 Colonel By Dr',
      startDate: new Date('2026-12-12T00:00:00'),
      endDate: new Date('2026-12-12T00:00:00'),
      startTime: '18:30',
      endTime: '23:00',
      isAllDay: false,
      isPrivate: false,
      category: 'social',
      createdBy,
    },
    {
      unionId,
      title: 'Christmas — Union Hall Closed',
      description: 'Union Hall offices closed for the Christmas holiday. Regular operations resume January 4th, 2027.',
      location: 'Union Hall',
      startDate: new Date('2026-12-25T00:00:00'),
      endDate: new Date('2027-01-02T00:00:00'),
      startTime: null,
      endTime: null,
      isAllDay: true,
      isPrivate: false,
      category: 'holiday',
      createdBy,
    },
    {
      unionId,
      title: 'Executive Board Year-End Meeting',
      description: 'Final executive board meeting of 2026. Year-end financial reconciliation, carry-forward items, and setting the January 2027 agenda.',
      location: 'Union Hall — Conference Room A',
      startDate: new Date('2026-12-08T00:00:00'),
      endDate: new Date('2026-12-08T00:00:00'),
      startTime: '17:00',
      endTime: '19:00',
      isAllDay: false,
      isPrivate: true,
      category: 'meeting',
      createdBy,
    },
  ];

  // Insert all events
  const insertedEvents = await db.insert(events).values(eventsData).returning();

  console.log(`\nSuccessfully created ${insertedEvents.length} events for CUPE Local 100 (2026)`);
  console.log('Events created:');
  insertedEvents.forEach((event, index) => {
    console.log(`  ${index + 1}. ${event.title} — ${event.startDate.toDateString()}`);
  });
}

seedCUPE100Events()
  .catch((error) => {
    console.error('Seed process failed:', error);
    process.exit(1);
  })
  .finally(() => {
    console.log('\nSeed process finished. Exiting...');
    process.exit(0);
  });
